language: swift
swift:
  - 4.0
  - 4.1

before_script:
  ##- pod install

script:
  - xcodebuild clean test -project App/RestaurantApp.xcodeproj -scheme RestaurantApp -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
